config:
  # Random seed.
  seed: 1

  # Shape we want for our moving images [width, height]
  shape: [50, 60]

  # Number of frames in a particular movement/animation/gif
  num_frames: 30

  # Number of movement/animations/gifs/sequences to generate
  num_sequences: 2

  # Real size of the images (eg: MNIST is 28x28)
  original_size: 28

  # Digits per movement/animation/gif/sequence.
  digits_per_image: 3

  # Boolean, used to decide if downloading/generating train set or test set
  training: True

  # Where to store the output
  dest: "./out"

  # Filetype for the generated data: "npz" or "jpg"
  filetype: "jpg"

  # Label type to produce: "coco" or "mots"
  # Use "coco" to train a detector (e.g. Mask R-CNN) like they were still images (it is still a sequence but each image is treaded independently)
  # Use "mots" to train a whole segmentation and tracking pipeline (includes track ids)
  labeltype: "coco"

  # Controls how much the size of a digit can change. <1 the percentage it can be smaller, >1 for bigger. 1 for the original size
  size_band: [0.7, 1.3]

  # Controls how fast the size changes. Should be [0, 1]. 0 for no change 1 for rapid change.
  size_change: 0.05

  # Highest and lowest bound for the random brightness of each digit
  brightness_band: [0.2, 1]

  # Delta brightness change. This controls how fast the brightness changes from frame to frame.
  # Should be in [0, 1], 0 for no change, 1 for a rapid change
  brightness_change: 0.05

  # Threshold for creating segmentation mask out of the original digit image
  seg_threshold: 124